import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const TIMESTAMP_PATTERN = /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/g
const TIMING_MS_CELL_PATTERN = /\| (\d+) \| (Yes|No) \|/g
const EPHEMERAL_BASE_URL_PATTERN = /https?:\/\/127\.0\.0\.1:\d+/g

export function normalizeGoldenContent(content: string): string {
  return content
    .replace(TIMESTAMP_PATTERN, '<TIMESTAMP>')
    .replace(TIMING_MS_CELL_PATTERN, '| <MS> | $2 |')
    .replace(EPHEMERAL_BASE_URL_PATTERN, '<BASE_URL>')
}

export function expectGoldenMatch(actual: string, golden: string, label: string): void {
  const normalizedActual = normalizeGoldenContent(actual)
  const normalizedGolden = normalizeGoldenContent(golden)
  if (normalizedActual === normalizedGolden) return
  const actualLines = normalizedActual.split('\n')
  const goldenLines = normalizedGolden.split('\n')
  const diffLines: string[] = []
  const maxLen = Math.max(actualLines.length, goldenLines.length)
  for (let i = 0; i < maxLen; i++) {
    if (actualLines[i] !== goldenLines[i]) {
      diffLines.push(`  line ${i + 1}:\n    golden: ${JSON.stringify(goldenLines[i] ?? '<missing>')}\n    actual: ${JSON.stringify(actualLines[i] ?? '<missing>')}`)
    }
  }
  throw new Error(
    `Golden mismatch for ${label} (${diffLines.length} line(s) differ):\n${diffLines.join('\n')}\n\n--- FULL NORMALIZED ACTUAL ---\n${normalizedActual}\n\n--- FULL NORMALIZED GOLDEN ---\n${normalizedGolden}`,
  )
}

export function compareOrUpdateGoldenFile(actual: string, goldenPath: string, label: string): void {
  if (process.env.UPDATE_GOLDEN === '1') {
    mkdirSync(dirname(goldenPath), { recursive: true })
    writeFileSync(goldenPath, actual)
    return
  }
  if (!existsSync(goldenPath)) {
    throw new Error(
      `No golden file at ${goldenPath} for ${label}. Golden files are created deliberately, not auto-generated by a passing run — review the real output once, then rerun with UPDATE_GOLDEN=1 to write it.`,
    )
  }
  const golden = readFileSync(goldenPath, 'utf-8')
  expectGoldenMatch(actual, golden, label)
}

export function compareOrUpdateGoldenDir(actualDir: string, goldenDir: string, label: string): void {
  const actualFiles = existsSync(actualDir) ? readdirSync(actualDir).sort() : []
  if (process.env.UPDATE_GOLDEN === '1') {
    rmSync(goldenDir, { recursive: true, force: true })
    mkdirSync(goldenDir, { recursive: true })
    for (const fileName of actualFiles) {
      writeFileSync(join(goldenDir, fileName), readFileSync(join(actualDir, fileName), 'utf-8'))
    }
    return
  }
  if (!existsSync(goldenDir)) {
    throw new Error(
      `No golden directory at ${goldenDir} for ${label}. Golden files are created deliberately, not auto-generated by a passing run — review the real output once, then rerun with UPDATE_GOLDEN=1 to write it.`,
    )
  }
  const goldenFiles = readdirSync(goldenDir).sort()
  if (JSON.stringify(actualFiles) !== JSON.stringify(goldenFiles)) {
    throw new Error(`Golden mismatch for ${label}: file set differs.\n  actual: ${actualFiles.join(', ')}\n  golden: ${goldenFiles.join(', ')}`)
  }
  for (const fileName of actualFiles) {
    const actual = readFileSync(join(actualDir, fileName), 'utf-8')
    const golden = readFileSync(join(goldenDir, fileName), 'utf-8')
    expectGoldenMatch(actual, golden, `${label}/${fileName}`)
  }
}
